name: pudge
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  gap: ^3.0.1
  flutter_svg: ^2.1.0
  google_fonts: ^6.2.1
  flutter_staggered_grid_view: ^0.7.0

  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  google_sign_in: ^6.3.0

  connectivity_plus: ^6.1.4
  dio: ^5.8.0+1
  hive: ^2.2.3
  flutter_secure_storage: ^9.2.4
  rxdart: ^0.28.0

  go_router: ^15.2.3
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  photo_view: ^0.15.0
  shimmer: ^3.0.0
  share_plus: ^11.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  build_runner: ^2.5.0
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.5

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore