// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCErj5xeu_-ZjFwIK6XyM4Vef-moujqOI8',
    appId: '1:1085786254751:web:9066dd45467a584532a1aa',
    messagingSenderId: '1085786254751',
    projectId: 'pudge-cce62',
    authDomain: 'pudge-cce62.firebaseapp.com',
    storageBucket: 'pudge-cce62.firebasestorage.app',
    measurementId: 'G-H8D8CQB9Y7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPvWhvYNOvfVEeTOTbjjhIJIbDjJhvbmA',
    appId: '1:1085786254751:android:31d8114284c07f4f32a1aa',
    messagingSenderId: '1085786254751',
    projectId: 'pudge-cce62',
    storageBucket: 'pudge-cce62.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe0XTBG08S6bklwNX5ZqSzUQtsx7FkBmg',
    appId: '1:1085786254751:ios:6a121e5da221003932a1aa',
    messagingSenderId: '1085786254751',
    projectId: 'pudge-cce62',
    storageBucket: 'pudge-cce62.firebasestorage.app',
    iosBundleId: 'com.example.pudge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe0XTBG08S6bklwNX5ZqSzUQtsx7FkBmg',
    appId: '1:1085786254751:ios:6a121e5da221003932a1aa',
    messagingSenderId: '1085786254751',
    projectId: 'pudge-cce62',
    storageBucket: 'pudge-cce62.firebasestorage.app',
    iosBundleId: 'com.example.pudge',
  );
}
